version: "3.7"

services:
  db:
    image: postgres:13.1-alpine
    container_name: db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - db-data:/db-data
    env_file:
      - .env

  main:
    build:
      context: .
      dockerfile: store/Dockerfile
    container_name: main
    working_dir: /main/
    restart: always
    volumes:
      - ./store:/main/
    command: bash -c "python manage.py collectstatic --no-input && python manage.py runserver 0.0.0.0:8000"
    depends_on:
      - db
    ports:
      - "0.0.0.0:8000:8000"
    env_file:
      - .env
volumes:
  db-data: