version: "3.7"

services:
  db:
    image: postgres:13.1-alpine
    container_name: db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    expose:
      - 5432
    volumes:
      - db-data:/db-data
    env_file:
      - .env

  main:
    build:
      context: .
      dockerfile: store/Dockerfile
    container_name: main
    working_dir: /main/
    restart: always
    volumes:
      - ./store:/main/
    command: bash -c "python manage.py collectstatic --no-input && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    depends_on:
      - db
    ports:
      - "0.0.0.0:8000:8000"
    env_file:
      - .env

  data_generator:
    build:
      context: .
      dockerfile: data_generator/Dockerfile
    container_name: data-generator
    working_dir: /data_generator/
    restart: always
    volumes:
    - ./data_generator:/app/
    ports:
    - "0.0.0.0:8001:8001"

volumes:
  db-data:
