version: "3.7"

services:
  db:
    image: postgres:13.1-alpine
    container_name: db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - db-data:/db-data
    env_file:
      - .env

  main:
    build:
      context: store/
      dockerfile: Dockerfile
    container_name: main
    working_dir: /store/
    restart: always

    volumes:
      - store:/store
    command: bash -c "python manage.py collectstatic --no-input && gunicorn store.wsgi:application --bind 0.0.0.0:8000 --workers=${GUNICORN_WORKERS_COUNT} --timeout=120 --log-level=debug"
    depends_on:
      - db
    ports:
      - "8000:8000"
    env_file:
      - .env
volumes:
  db-data:
  store: