# Generated by Django 3.1.5 on 2021-07-20 14:45

import api.validators
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemInOrderRelationship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveSmallIntegerField(validators=[api.validators.validate_min_amount_of_items_in_orders])),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders_with_item', to='api.item')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paid', models.BooleanField(default=False)),
                ('sold_for', models.PositiveIntegerField(null=True)),
                ('items', models.ManyToManyField(null=True, related_name='orders', through='api.ItemInOrderRelationship', to='api.Item')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='iteminorderrelationship',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items_in_order', to='api.order'),
        ),
    ]
