# Generated by Django 3.1.5 on 2021-07-20 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210720_1745'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='returned_amount',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
