# Generated by Django 3.1.5 on 2021-07-20 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_item_returned_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='items',
            field=models.ManyToManyField(blank=True, related_name='orders', through='api.ItemInOrderRelationship', to='api.Item'),
        ),
    ]
