# Generated by Django 3.1.5 on 2021-07-20 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20210720_2159'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='sold_at',
            field=models.DateField(null=True),
        ),
    ]
